name: vega_embed_flutter_demo_page
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  vega_embed_flutter: ^0.1.0
  http: ^0.12.0+4

  flutter_portal: ^0.0.1+2

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.14.2

flutter:
  uses-material-design: true
  assets:
    - js/
    - css/
    - vega_lite_specs/single_view_plots/bar_charts/
    - vega_lite_specs/single_view_plots/histograms/
    - vega_lite_specs/single_view_plots/scatter_plots/
    - vega_lite_specs/single_view_plots/line_charts/
    - vega_lite_specs/composite_marks/error_bars_and_bands/
    - vega_lite_specs/composite_marks/box_plots/
    - vega_lite_specs/interactive/interactive/
    - vega_lite_specs/interactive_multiview/multiview/
    - vega_lite_specs/layered_plots/labeling_annotation/
    - vega_lite_specs/maps/geo/
    - vega_lite_specs/multi_view_displays/repeat_and_concatenation/
    - vega_lite_specs/multi_view_displays/trellis/